apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hapi-rs
  namespace: hapi-ns
  labels:
    app: hapi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hapi
  template:
    metadata:
      labels:
        app: hapi
    spec:
      containers:
      - name: echo
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080